// scripts/seed-admin.mjs
// Usage: node scripts/seed-admin.mjs admin@example.com "your-password"
// Then run: wrangler d1 execute bmi-portal-db --file=seed-admin.sql

const email = process.argv[2];
const password = process.argv[3];

if (!email || !password) {
  console.error('Usage: node scripts/seed-admin.mjs <email> <password>');
  process.exit(1);
}

async function hashPassword(password) {
  const salt = crypto.getRandomValues(new Uint8Array(16));
  const keyMaterial = await crypto.subtle.importKey(
    'raw', new TextEncoder().encode(password), { name: 'PBKDF2' }, false, ['deriveBits']
  );
  const hashBuffer = await crypto.subtle.deriveBits(
    { name: 'PBKDF2', salt, iterations: 100000, hash: 'SHA-256' }, keyMaterial, 256
  );
  const saltHex = Array.from(salt).map(b => b.toString(16).padStart(2, '0')).join('');
  const hashHex = Array.from(new Uint8Array(hashBuffer)).map(b => b.toString(16).padStart(2, '0')).join('');
  return `pbkdf2:${saltHex}:${hashHex}`;
}

const userId = crypto.randomUUID();
const passwordHash = await hashPassword(password);
const now = new Date().toISOString().replace('T', ' ').slice(0, 19);

const sql = `-- Seed admin user (generated by scripts/seed-admin.mjs)
INSERT OR IGNORE INTO users (id, email, password_hash, first_name, last_name, role, is_verified, created_at, updated_at)
VALUES ('${userId}', '${email}', '${passwordHash}', 'Admin', 'User', 'admin', 1, '${now}', '${now}');

-- Verify
SELECT id, email, role, is_verified FROM users WHERE email = '${email}';
`;

console.log(sql);
